name: bill_splitter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flux: ^4.1.3
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
